### ISSUE TITLE
getAppContentStageSharingState returning wrong value in ipados

### ISSUE THREAD

**Issue by xerosanyam** [OfficeDev/microsoft-teams-library-js#1281]
Even when I am not presenting, `getAppContentStageSharingState` is returning 
```
err: null

result:
{
isAppSharing:true
}
```

More info:
```
hostClientType: 'ipados'
```

reference: https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#get-app-content-stage-sharing-state-api

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - We will check this scenario at our end and let you know the updates.

**Comment by xerosanyam** [comment]
@Nivedipa-MSFT any work arounds you can think of by then?

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - The isAppSharing is true whenever there is sharing happening. Can you please check if there is any other user is sharing the screen in meeting?

**Comment by xerosanyam** [comment]
> Can you please check if there is any other user is sharing the screen in meeting?

I did check. only I was sharing

@Nivedipa-MSFT isAppSharing always comes as true (whether its sharing or not), that's the problem that I reported.
check you please check if `isAppSharing` is coming as `false` when sharing is not happening?

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - Apologies for delay response. We need two apis to complete the stop sharing flow complete from apps. We need stop sharing api as well as stop sharing subscriptions. Stop sharing subscription is needed incase user clicks on stop sharing button on ubar or some other users starts sharing session that will kill the current sharing session and start a new sharing. In both case, app need to know the stop sharing happened and they can change their UI. Without subscription api, just stop sharing api is not complete. Because of this you are getting isAppSharing is true.

**Comment by xerosanyam** [comment]
@Nivedipa-MSFT thanks for providing more insights about the issue. As this looks like a major bug, can we apply appropriate labels and also update the documentation accordingly, thanks.

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - Engineering team is looking into it. It will be released in near future.

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - We are checking this internally. We will update you soon.
