### ISSUE TITLE
Error: unknownAuthError from authentication.getAuthToken()

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#1307]
Hi Teams SDK teams,

I did set up according to the repo you mentioned ([OfficeDev/msteams-tabs-sso-sample-nodejs](https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs)).

The response from `authentication.getAuthToken()` function is `Error: unknownAuthError`

i'm using the library: `@microsoft/teams-js: "^2.0.0"`
 
We are testing on Teams Desktop client (both Windows and MacOS).

Version 1.5.00.22260. It was last updated on 16/08/2022.

**Expected**

I can get tokens from the current user logged in on Teams Desktop App without an error or a login popup.

Thanks

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - Is there any console error you are getting?

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - Could you please confirm if you have the following Graph permissions enabled: `email,` `offline_access`, `openid`, `profile`, and `User.Read` ?
Mostly it fails because the user hasn't granted permission to access the API.

**Comment by Prasad-MSFT** [comment]
As mentioned
`/auth/token` does not render anything but instead is the server-side route for initiating the [on-behalf-of flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-on-behalf-of-flow).
-It takes the token it receives from the `/ssoDemo` page and attempts to exchange it for a new token that has elevated permissions to access the profile Graph API (which is usually used to retrieve the users profile photo).
-If it fails (because the user hasn't granted permission to access the profile API), it returns an error to the `/ssoDemo` page. This error is used to display the "Consent" button which uses the Teams SDK to open the `/auth/start` page in a pop-up window.
`/auth/start` and `/auth/end` routes are used if the user needs to grant further permissions.

**Comment by Prasad-MSFT** [comment]
_**Reason:**_ The error occurs because a silent sign in is sent to the login.microsoftonline.com endpoint, however the AAD SSO cookie is not being detected. This cookie determines if the user is logged in or not. The silent sign in is only meant to be used if the user is already known to be logged in or has a refresh token to exchange for a new access token.

Possible Resolution 1: Proactively Check for Expiration You can attempt to prevent this error from ever occurring by checking if you have a valid id token. If you're ID token is not valid, you will ask the user to login again.

Possible Resolution 2: Catching the Error and Asking the User to Login Again To resolve this error you will need to catch this error in a callback that you can pass into the acquiretoken ADAL JS function. If the AADSTS50058 error occurs, you'll ask the user to login again.

Possible Resolution 3: Browser Extension Cookie Blockers and Third Party Cookies Disabled Some users may experience this issue due to a browser extension that is blocking cookies for tracking purposes. This will cause this AADSTS50058 error to occur, you will need to whitelist the login.microsoftonline.com endpoint in your browser extension in order to avoid receiving this error again.

This error can also occur if the third party cookies have been disabled in your browser. Re-enable third party cookies in your browser to prevent this error from occurring.

**Comment by iamsahilralkar** [comment]
hi!.

I'm also getting the same issue that is 'unknownAuthError' for microsoftTeams.authentication.getAuthToken() method.
I've given all the required permission to access API.
The same method works in teams desktop app without an error and has a issue only in web browser app.
![image](https://user-images.githubusercontent.com/23616296/186600660-c881a1c7-82ab-4016-9624-4954b159b145.png)

**Comment by iamsahilralkar** [comment]
> Hi @iamsahilralkar please try add two client applications to `Authorized client applications` in Azure Portal. This is for the Teams desktop/mobile clients and the web client.
> 
> ```
> 5e3ce6c0-2b1f-4285-8d4b-75ee78787346
> 1fec8e78-bce4-4aaf-ab1b-5451cc387264
> ```

Worked. Thanks for solution.
