### ISSUE TITLE
tokenRevoked InternalError

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/microsoft-teams-library-js#1343]
Hi All,

We are seeing the error below when using teams authentication. Im unable to find any information online to help determine the cause of the issue. We have thousands of people daily who are able to authenticate but 24% of our users cannot authenticate due to this issue. 

```
n.InternalError: Get SSO token failed with error: tokenRevoked,n.InternalError: Get SSO token failed with error: tokenRevoked
    at Object.failureCallback 
```

**Comment by sayali-MSFT** [comment]
@AnthonyPhan - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@AnthonyPhan -Are you getting this error back from the getAuthToken API ?  Could you please shared Teams client logs showing the issue for us to review? 
Typically, this error happens when user interaction is required but the develop is trying to call getAuthToken with the silent parameter set to true. You need to call getAuthToken again with silent set to false in order to get a token:
Reference Document - https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.authentication.authtokenrequest?view=msteams-client-js-1.12.1#@microsoft-teams-js-microsoftteams-authentication-authtokenrequest-silent
