### ISSUE TITLE
Another approach to get client token from Teams App instead of "getAuthToken()"

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#1400]
Because SSO Tab auth flow just supports only one domain, we face an issue with implementing multiple domains within one Teams app to production.

Example:
- If i use a domain different from `Expose an API` in App Registration.

Expose an API: `api://web.abc.dev/6b683be2-933f-4704-9f06-f9e5dbbb7541`
Tab on Teams: `web.123.dev`

it will show `App resource defined in a manifest and iframe origin do not match`.

So can you guys propose any other approach by requesting API or some way to replace `resource` in `webApplicationInfo` of the manifest file to get client token from Teams App?

Many thanks

**Comment by sayali-MSFT** [comment]
@tiennguyen1293 - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by iambmelt** [comment]
Hi @tiennguyen1293 - Thanks for reaching out with this question.

At this time, the programming model is restricted to a single domain which hosts/serves the application due to the security model; this ensures that the service for which `getAuthToken()` acquires an access token is owned by your application.

We are aware that this restriction creates a developer experience challenge and are currently exploring future platform capabilities that will remove this restriction.

If your application needs to call multiple services across different domains, you should use a mid-tier service to act as a proxy layer.

![image](https://user-images.githubusercontent.com/990063/196308245-0d488060-be21-4fc7-ab3b-783d853c67b2.png)

Alternatively, if you have different environments for dev, test, prod, etc. you might consider templatizing your apps manifest and using your build process to select or deploy a configuration.
