### ISSUE TITLE
How to handle Azure Ad SSO in desktop app

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/microsoft-teams-library-js#141]
Hi,

I have an issue with the desktop app only. We handle SSO connection with back-end service and passport azure ad, so when the user is not logged in I just replace the current window.location to redirect him to our sso login endpoint, which then handle things with passport.

It works very well from teams in browser, but it fails in the desktop application, being stuck on a white page.

Is there some usage of the API I missed?

**Comment by ydogandjiev** [comment]
The behavior you are seeing is expected because unlike in the browser, there typically isn’t an active AAD session in the Teams desktop client. We have some pretty detailed documentation on how you can modify your auth solution to work well in Teams:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-AAD

To get an SSO-like experience in your tab that minimizes the amount of times a user has to go through the auth flow you can follow the instructions here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-AAD

**Comment by billbliss** [comment]
The `microsoftTeams.authentication.authenticate` API works in the browser and the desktop. There's no need to distinguish between the two in your code - use it all the time.

**Comment by JSteunou** [comment]
@billbliss Chrome does not agree. By default it blocks the popup and user experience is degraded. You have to be a light power user to see that a popup is blocked and can be shown.

I did go around by acting differently between browsers or Electron

**Comment by billbliss** [comment]
OK, I see what you mean for silent auth - you want to just call a function and get back a token. 

Normally we are very clear in our app guidelines that signin needs to be initiated by the user but that's the whole point: to avoid making the user do anything. 

We're working on making real SSO a first-class scenario but it's a challenge from a security standpoint.

**Comment by ydogandjiev** [comment]
@JSteunou, the way you can implement this functionality is by using ADAL to attempt to fetch an auth token silently. Then if that fails you display a “Sign in” button that when clicked calls microsoftTeams.authentication.authenticate to do the full auth flow within a popup window. This flow is described in the second link I shared out above.

**Comment by JSteunou** [comment]
To be clear, I dont want the user to be logged into Azure Ad, I'm mean, it's a way, but not the end. So I dont need getting a token, or silent auth, I think.

I want the user to be logged on *my* platform, (like Trello does for example) but *through* our Azure Ad SSO endpoint instead of just login/password

**Comment by billbliss** [comment]
Got it, thanks for the clarification.

**Comment by JSteunou** [comment]
For example, in a browser, I can just do `window.location = 'https///myplatform.com/sso/aad&redirect=${window.location}'` and the user is logged through Azure Ad on our platform, so he can access some data and configure its tab.

In the desktop app it just does not work, blank page after redirection.

So I did a simple `if (isElectron())` base on user agent to play with `microsoftTeams.authentication.authenticate`. It opens Chrome browser (I expected an still in electron popup), allows me to log in, but it does not close, nor see myself connected in the app.

If I remove my the check on Electron to debug this flow in browser, it works well, I have a popup, can log in, it then closes after calling notify. The only drawbacks is that the popup is blocked by default.

So again, it works in browser, not in desktop.

**Comment by JSteunou** [comment]
I update a little bit my previous statement: use the app, the *popup* (dont know if we can still call a full Chrome browser a popup) close after calling `notifySuccess` but the main tab configuration screen does not have the successCallback called, nor the cookie token from my platform set.

**Comment by billbliss** [comment]
Are you trying to call `microsoftTeams.authentication.authenticate` with `https://myplatform.com/sso/aad/redirect=${window.location}`? 

That won't work - you need to have a stub page so that there's something for AAD to redirect back to (that's the problem) here. That's described [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad#include-and-configure-adal) - see also the source from the [Node.js sample](https://github.com/OfficeDev/microsoft-teams-sample-complete-node) - in particular [these](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/tree/master/src/views/tab-auth).

**Comment by JSteunou** [comment]
I ll try this but I find it very odd. I have other sso endpoints for Google Facebook etc... And they do work perfectly fine by just replacing `window.location`. I m curious about why Microsoft works differently (who says the hard way 😇)

**Comment by billbliss** [comment]
They work within the Teams client? That's the issue here, not Azure AD.

**Comment by JSteunou** [comment]
Yep they do. That s why I m trying every things I can try.

But the more I dig here the more I start to think it is an issue between the Teams Electron client and the Azure Ad SSO. An association between some electron options and azure add weird way of doing SSO (It needs to forward data through signed cookies whereas it calls the redirect uri as POST and could transmit in this call like others do)

**Comment by ydogandjiev** [comment]
> I'm not sure the solution you describe them can apply to us. Like I said, we are using back end implemented SSO logic, and I still dont get how this SDK popup / authentication / callback api can be used outside the scope you described, meaning with generic SSO flows and not just Microsoft Azure Ad flow and endpoints.

@aosolis, do you know if it's possible to get a Passport.js server-driven auth flow to work inside of a Teams tab? I think it should be relatively straightforward to have a login page with "Sign in with <provider>" buttons on it that when clicked call microsoftTeams.authentication.authenticate with the start URL for the auth flow and then add a microsoftTeams.authentication.notifySuccess call to the callback page. I just don't know how an SSO experience can be achieved in the cases where the user has already signed in with AAD/Google/Facebook.

**Comment by aosolis** [comment]
@JSteunou what Yuri described ought to work-- instead changing window.location to your SSO login endpoint directly, you'd instead go to a page with a button that when clicked calls `microsoftTeams.authentication.authenticate`.

This part of your previous response suggests your page is missing something:

> So I did a simple if (isElectron()) base on user agent to play with microsoftTeams.authentication.authenticate. It opens Chrome browser (I expected a still in electron popup), allows me to log in, but it does not close, nor see myself connected in the app.

> If I remove my check on Electron to debug this flow in a browser, it works well, I have a popup, can log in, it then closes after calling notify. The only drawbacks is that the popup is blocked by default.

I'd suggest calling `authenticate()` only when the user clicks on the login button, not automatically on page load. If you call it on page load:

1. In a browser, as you've seen, the popup will be blocked by the popup blocker.
2. In the desktop app there's no popup blocker, but you're likely to end up in a race condition in `authenticate()`. If `initialize()` hasn't returned yet, the page will fall back to calling `window.open`, and in the Teams desktop app, that launches the URL **in a new browser**. That browser instance has no connection back to the Teams desktop app, so `notifySuccess()` will not work, nor will your app see the session established by passport.js. I think you were ending up in this state, because you report that your auth flow opened in a full Chrome browser, not an Electron popup window.

**Comment by JSteunou** [comment]
> @JSteunou, the reason why you are perceiving that your auth solution works in the browser is because you are already signed into Facebook or Google within the browser's session so when you redirect through their authentication endpoints they are able to generate an access token without prompting for credentials. If you were to sign out of Facebook or Google and attempt the same flow in your tab you will see it fail in the same way as it does in our Electron client. That's because credential entry pages return the X-Frame-Options: DENY header preventing the browser from rendering them inside of an iframe.

@ydogandjiev just tried and indeed you're right. I now understand better the limitation I'm facing in Electron.

@aosolis I'll try that.

Thank you guys, I really appreciate your help!

**Comment by JSteunou** [comment]
Hurray!! It works :)

For those having the same issue with the same flow (SSO handle by your back-end with passportjs for example) you have to

1. create a button for *sign in to <MyApp> with <Provider>*
2. onClick use `microsoftTeams.authentication.authenticate` with `{url: <your backend sso url for the said provider>, successCallback: <a callback that will start again your config app>}`
3. a *end of sso login* page which will call `microsoftTeams.authentication.notifySuccess`.

Tricks

1. If your provider is Azure Ad you can use *hint* so the user is not forced to type its email again. It is a plus but the best would have been to be auto-log because already logged in Teams with the same account
2. You can use the same page for the config app and the *end of sso login* app by just checking if you are not in an iframe before calling `microsoftTeams.authentication.notifySuccess`. This as the advantage to not make specific development in your backend, and use an already all microsoft packaged ready application ;)

Again thank you for your times @ydogandjiev & @aosolis :)

**Comment by billbliss** [comment]
Excellent!

**Comment by paddotk** [comment]
As this is a workaround, not a solution, I suggest to open this issue again. In my opinion this needs an actual solution to also work in the desktop app without needing to click a button.
