### ISSUE TITLE
Missing parentMessageId in Context.app when opening TaskModule with MessagingExtension

### ISSUE THREAD

**Issue by msmichaelwoo** [OfficeDev/microsoft-teams-library-js#1421]
Hello,

Previously our app used Teams-JS V1, and we could launch our TaskModule using a MessagingExtension App to get the parentMessageId from context.parentMessageId.

Updating to V2, we're trying to do the same, but the context.app.parentMessageId is now empty. I see in the documentation that this id is only populated from bot interactions, is this expected behaviour?

**Comment by Nivedipa-MSFT** [comment]
@msmichaelwoo  - We are checking this internally. We will update you soon.

**Comment by AE-MS** [comment]
Hi @msmichaelwoo, thanks for reporting this issue. I was investigating it based on what you said but I wanted to be sure I understood the exact scenario you were trying since there are a number of different ways for messaging extensions, adaptive cards, and task modules (dialogs) to interact.

Can you provide just a bit more detail on the scenario that exposing the empty `parentMessageId` behavior? You have an ME app, is it posting an adaptive card into a message, and then interacting with that adaptive card triggers the bot to show a task module? Or is it different than that?

Thanks!

**Comment by AE-MS** [comment]
After some offline discussion, we established that this problem actually occurs in all versions of teams-js and not just V2 as originally indicated. Furthermore, this issue appears to only occur on specific versions of Teams. We will continue to follow-up.

**Comment by AE-MS** [comment]
This does not need author feedback; I have cleared that tag.

**Comment by Nivedipa-MSFT** [comment]
@msmichaelwoo - We are checking the bug status with the engineering team. We will let you know once we have any update.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by nwojod-MSFT** [comment]
This issue has been resolved internally. We are closing it now.
