### ISSUE TITLE
cannot update `allow` attributes in task module

### ISSUE THREAD

**Issue by xhb1987** [OfficeDev/microsoft-teams-library-js#1424]
Hi,

In our platform, we allow user to embed youtube video and auto play the video.

And this autoplay is not working inside the teams task module, I have checked the task module `iframe` attributes, seems there is no attribute like `allow="autoplay"`, and I tried to update this attribute, but there is no way to do it.

Is there any way to modify this attribute?

**Comment by Prasad-MSFT** [comment]
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by alicialu-MSFT** [comment]
Hi xhb1987! 

We understand the importance of this feature and have added it to our backlog. The team will review it, the level of work required, and prioritize accordingly. Because of the volume of requests we receive, we are unable to promise when this feature will be implemented. We will provide an estimate on this thread as soon as we have a committed timeline.

In the meantime, could you provide some more context on the user scenario? Does this error occur during meetings?

**Comment by alicialu-MSFT** [comment]
Hi @xhb1987 , as a follow up, could you elaborate on which platforms and clients you are trying to make the youtube video work for?

**Comment by xhb1987** [comment]
Hi @alicialu-MSFT, sorry for the late reply.

We are using MS Kahoot app to host a live game on the task module

**Comment by alicialu-MSFT** [comment]
Hi @xhb1987, we have addressed your feature request. Please expect to see this change to be available in the coming weeks.
