### ISSUE TITLE
In meeting app - side panel close event

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/microsoft-teams-library-js#1530]
is there event to detect when user close the side panel of meeting apps. ? 
I tried beforeunload event. however, it doesn't seem to function

` $(window).on("beforeunload", function () { });`

![image](https://user-images.githubusercontent.com/5784846/212260232-ae96f3c7-3ad6-42e3-bd57-f6da04e4cdba.png)

**Comment by ChetanSharma-msft** [comment]
Hello @asith-w - Thanks for raising your issue.
We will investigate on your query and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@asith-w - You can use microsoftTeams.teamsCore.registerOnLoadHandler. We tested this in "@microsoft/teams-js": "^2.5.0". It is getting called when a meeting side panel is closed. 
Please note that there is an open bug for this on mobile - https://github.com/OfficeDev/microsoft-teams-library-js/issues/1445#issuecomment-1326014138

**Comment by alexneyman-MSFT** [comment]
@asith-w -- Apologies for the delayed update. There is currently no support for getting the sidepanel close event. We're actively developing support for unloading events, including this side panel close event as well as unloading events for switching away from full applications running in the side bar (outside of meetings). The currently available handlers `registerBeforeUnloadHandler` and `registerOnLoadHandler` are currently marked for internal use because there is no guarantee that they are working. As of today they do not do anything but we are actively working on supporting them soon.
