### ISSUE TITLE
[Feature request] Add action menu API for application to show custom native action menu.

### ISSUE THREAD

**Issue by ErythroME** [OfficeDev/microsoft-teams-library-js#1538]
There's a scenario in our application, when we want to show a custom native action menu to our users, providing some options like "Share", "Save" etc. 

This would improve user experience a lot by providing a more native-like experience to users.

So, it'll be very convenient if Teams JS SDK could add an interface API for custom action menu. Thanks!

**Comment by nwojod-MSFT** [comment]
Hi @ErythroME, Thank you for raising this request, we understand the importance of this feature and have added it to our backlog. The team will review it, the level of work required, and prioritize accordingly. Because of the volume of requests we receive, we are unable to promise when this feature will be implemented. We will provide an estimate on this thread as soon as we have a committed timeline.

**Comment by nwojod-MSFT** [comment]
Requesting team opted to implement their own custom dialog.
