### ISSUE TITLE
getTabInstances() expected behavior

### ISSUE THREAD

**Issue by bajzat** [OfficeDev/microsoft-teams-library-js#154]
Hi!

In my application, I have one or more configurable tabs and a personal tab where I'd like to see the list of the configured tabs. According to the SDK documentation, the getTabInstances call should return with the array of the tabs which are owned by my app. 

The current behaviour is the API call returns with an empty array if I execute the API call on a personal tab and returns with an array which contains the tab itself on a configurable tab.

Thanks,

Tamas

**Comment by ydogandjiev** [comment]
This is happening because each time you upload your app package into a team or personally we create a unique app instance for you with its own unique app ID and the `getTabInstances` API only fetches the configured tabs for that unique app ID. When your app is submitted to the Teams Store you won't have this issue because at that time all instances of your app installed across different teams and users will share the same global app ID.

Your best option for testing this functionality out in development is to upload your app package into a single team. Create several different instances of the app's configurable tab in multiple channels within that team. Then search for the app from the power bar and navigate to it:
![image](https://user-images.githubusercontent.com/3357245/48364170-979f9d80-e65c-11e8-9750-e61d3381f50b.png)

Finally, install the same app personally by clicking on the Add button in the banner at the top:
![image](https://user-images.githubusercontent.com/3357245/48363996-16e0a180-e65c-11e8-91de-4a6d097d9ac4.png)

This will ensure that the same app instance is installed both in your team and personally; then when you call `getTabInstances` from the app's personal tab you should get all of the app's configurable tab instance from the team.

P.S. There might be a way for us to simplify the development story here by keying off of the developer-provided ID in each of the apps and stitching together the tab instances across multiple apps uploaded to different teams. Will throw an item in our backlog for this.

**Comment by bajzat** [comment]
Thanks for your help and explanation.
