### ISSUE TITLE
[Feature request] Add APIs to support opening native share panel in Android Webview.

### ISSUE THREAD

**Issue by ErythroME** [OfficeDev/microsoft-teams-library-js#1540]
On iOS platform, we can use [.share()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) and [.canShare()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare) in WebView to invoke native share panel, but Android WebView doesn’t support them, so we need similar APIs powered by Teams JS SDK.

Those APIs will improve user experience by helping them share their interests to others.

**Comment by nwojod-MSFT** [comment]
@ErythroME, thank you for raising this request. We have added it to our backlog, and we will review it, the level of work required, and prioritize accordingly. We will provide an estimate on this thread as soon as we have a committed timeline. In the meantime, can you let us know what version of the Teams JS SDK you are running.

**Comment by ChetanSharma-msft** [comment]
Hello @ErythroME - 
Hope you are doing well!!

Could you please let us know what version of the Teams JS SDK you are running?

**Comment by sakov-ms** [comment]
Hi @ErythroME 

Hope you are doing well!

We have identified a few workarounds for this feature on Android. Please see if any of these work for you.

Option #1: If you are using a secondary webview, then you can use this --> https://developer.chrome.com/docs/android/custom-tabs/browser-support/#setShareState

Option #2: You can also use our Copy to Clipboard API (https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest). This will open a dialog with the URL instead of invoking share tray and users can copy the link and paste in their destination apps.
