### ISSUE TITLE
How to use the non deprecated version of authentication.authenticate ?

### ISSUE THREAD

**Issue by FE-POLY** [OfficeDev/microsoft-teams-library-js#1674]
Hi everyone,

In my React application, I'm importing `authentication` to use its `authenticate` method. I get a warning that this method is deprecated and that I should use its new version. But since both version are called `authentication.authenticate()`, how can I call the right method ?

**Comment by AE-MS** [comment]
> Hi everyone,
> 
> In my React application, I'm importing `authentication` to use its `authenticate` method. I get a warning that this method is deprecated and that I should use its new version. But since both version are called `authentication.authenticate()`, how can I call the right method ?

Hi @FE-POLY! I would think that most tools should be able to disambiguate between whether or not you're calling the deprecated overload based on the parameters/calling pattern. For example, in VS code I can call both and it disambiguates between the deprecated and non-deprecated one:

![image](https://user-images.githubusercontent.com/36546967/228314637-a9d516cd-7760-40d6-a5b1-6942037ca490.png)

(the first two examples have the strikethrough because it recognizes that I'm calling the deprecated overload, whereas the third and fourth do not since they are the non-deprecated ones)

Can you say more about where the warning is coming from (e.g., which tool is showing you the warning)? And give an example of how you are calling the method?

Thanks!

**Comment by FE-POLY** [comment]
Hi @AE-MS and thank you for your answer.
I'm using VS Code. Yesterday, when I created this issue, `authenticate` had the strikethrough bot today, without changing anything, it looks clean and it's not marked as deprecated when I hover it.
For information, this is my code :
```js
await microsoftTeams.authentication.authenticate({
  url: "https://www.example.com",
  width: 600,
  height: 555,
  isExternal: true,
});
```

**Comment by AE-MS** [comment]
> Hi @AE-MS and thank you for your answer. I'm using VS Code. Yesterday, when I created this issue, `authenticate` had the strikethrough bot today, without changing anything, it looks clean and it's not marked as deprecated when I hover it. For information, this is my code :
> 
> ```js
> await microsoftTeams.authentication.authenticate({
>   url: "https://www.example.com",
>   width: 600,
>   height: 555,
>   isExternal: true,
> });
> ```
> 
> I just noticed that the `initialize` method is still marked as deprecated. Here's how it is implemented :
> 
> ```js
> const initializeTeamsApp = (): void => {
>   if (isDisplayedInTeams()) {
>     microsoftTeams.initialize();
>   }
> };
> ```

Sorry for the inconsistent VS Code behavior around `authenticate` -- not sure why that was happening. Nonetheless, it looks like your current call is correct to me and using the non-deprecated version.

For your call to `initialize`, while I can't see your `import` statements, it looks like you might be calling the deprecated `initialize` function located [in the root](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-initialize) of the teamsjs library rather than [the one in the app namespace](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize), which is the newer, non-deprecated one.

Note: with both the non-namespaced `initialize` and the one in the `app` namespace, you have to wait until it completes (as indicated by either the provided callback being called or the promise being resolved) before calling any other functions in the teamsjs library. If your app doesn't wait until `initialize` is completed, there will be a race condition and other functions may fail seemingly randomly.

Does that help?

**Comment by AE-MS** [comment]
Great, glad we were able to get to the bottom of it!
