### ISSUE TITLE
Prefetch Shopping app 

### ISSUE THREAD

**Issue by Shama-Bildikar** [OfficeDev/microsoft-teams-library-js#1714]
The shopping app team is requesting the app bundle to be prefetched when user opens Outlook Mobile app (Android and iOS). This will reduce latency of app load when user clicks on shopping app.

**Comment by nwojod-MSFT** [comment]
@Shama-Bildikar thank you for submitting this request and we have added it to our backlog. The team will review it, the level of work required, and prioritize accordingly. Because of the volume of requests we receive, we are unable to promise when this feature will be implemented. We will provide an estimate on this thread as soon as we have a committed timeline.

**Comment by nwojod-MSFT** [comment]
This is not a TeamsJS feature ask, but Outlook mobile. Feature request raised with Outlook mobile team.
