### ISSUE TITLE
How to force tab title update & channel message update

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/microsoft-teams-library-js#181]
When a channel user add a tab, the `suggestedDisplayName` is used for the tab's title, but if the user configure the tab again a change the settings, the new `suggestedDisplayName` is not used.

I found out it is *on purpose* reading this lib types

```ts
            /**
             * A suggested display name for the new content.
             * In the settings for an existing instance being updated, this call has no effect.
             */
            suggestedDisplayName?: string;
```

**But** I do not understand this choice.

Why on new settings not updating the tab title and publish a new message on the channel?

And how I can achieve to get this behavior?

**Comment by Gousia-MSFT** [comment]
@JSteunou Thanks for reaching out to us. This is a known issue and we have raised a bug for this.

**Comment by Wajeed-msft** [comment]
The behavior described in this issue is by design. We only allow users to rename tabs via the Teams UI in order to ensure that the experience is always predictable and tabs don't just "disappear" because their name changed without the user's awareness.

Entry point for renaming:
![image](https://user-images.githubusercontent.com/31851992/95736696-2e8b8f00-0ca4-11eb-9d5c-ee88618d8084.png)


Tab rename dialog:
![image](https://user-images.githubusercontent.com/31851992/95736720-364b3380-0ca4-11eb-89fe-bfc6e17900a3.png)
