### ISSUE TITLE
Settings for a Teams toolkit app deployed to a blob storage in Azure

### ISSUE THREAD

**Issue by AlbertoPerez8** [OfficeDev/microsoft-teams-library-js#1955]
Currently I have a communications app deployed to Azure in a blob storage, and it previously went through some security inspections where I was given some recommendations on tightening security. These where to set default anonymous access to blob storage to be disabled, and for blob soft delete to be enabled. 

Would any of these measures affect my app's behavior, would conversations that run with Azure SDK be the data that would be stored and deleted, or are these settings more for the metadata/information regarding the blob storage resource itself?

The comms app is the first one being done with the teams toolkit, so my team and I don't have any real knowledge on how some settings in Azure affect the behavior and performance of apps.

**Comment by AE-MS** [comment]
The library supported here (teams-js) doesn't directly use or depend on Azure for anything when used in an app. As such, there's no specific knowledge or recommendation regarding how adjustting Azure settings might affect your app, since Azure usage will usually be specific to each app.

That said, since it sounds like you are using Teams Toolkit, and TTK does use Azure as part of it's bootstrapping and support, the Teams Toolkit team may be able to offer some suggestions. You can find them on their GitHub project [over here](https://github.com/OfficeDev/TeamsFx).

Also @therealjohn helps build TTK so tagging him so he might be able to help here.

**Comment by AE-MS** [comment]
Closing this issue so it can be transitioned to the other discussion location.
