### ISSUE TITLE
displayDialogAsync not opening in Outlook Android context

### ISSUE THREAD

**Issue by BryanCB1** [OfficeDev/microsoft-teams-library-js#2113]
Hello

We have a problem using the `displayDialogAsync` function in our plugin. What we are looking for on mobile devices is that our authentication window opens in the same context of the application and is not a browser window. This behavior works correctly on iOS devices but on Android devices this does not work correctly, in the same way on the web. and the desktop application works fine.

We are using the next library version script:
` <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
`

And we already checked and if the context is being obtained, the ui object does have the necessary elements, everything seems in order

Our implementation is executed listening to the click event in an html file, then the function that is in a js file is executed to trigger the dialog and perform the subsequent functions

Part of the html code:

`
                button.addEventListener("click", (event) => {
                    window.Handler.eventClickLogin()
                });
`

Part of the JS code:

`eventClickLogin: function(){
        Office.context.ui.displayDialogAsync(window.location.origin + window.Handler.oauthUrl + '?url=' + encodeURIComponent(dataUser.redirect), {
                height: 75,
                width: 30,
                promptBeforeOpen: false
            })
    }`

Finally we carry out a curious test, doing the test with a Wi-Fi network it works incorrectly, but when we do the test changing to mobile data everything works as we want.

https://github.com/OfficeDev/microsoft-teams-library-js/assets/153008575/5dd07f3b-3dac-4593-8bc0-683c907d4587

In the video, a couple of attempts are made connected to the Wi-Fi network and the behavior of displayDialogAsync is to open a browser tab, after that the Wi-Fi is turned off and one more execution is carried out, this time the displayDialogAsync function opens the url inside from a tab of the same plugin, that is the compartment we are looking for

We ask for your help to detect and solve this behavior

Greetings

**Comment by ChetanSharma-msft** [comment]
Hello @BryanCB1 - Looks like your issue is related to office JavaScript library.
Could you please raise your issue here? [
https://github.com/OfficeDev/office-js-docs-pr/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%203b5dc847-5ea4-9ec9-e855-224639ed6861%0A*%20Version%20Independent%20ID%3A%20d8c790b3-d886-91d2-8480-f01164a7a3aa%0A*%20Content%3A%20%5BUnderstanding%20the%20Office%20JavaScript%20API%20-%20Office%20Add-ins%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Foffice%2Fdev%2Fadd-ins%2Fdevelop%2Funderstanding-the-javascript-api-for-office)%0A*%20Content%20Source%3A%20%5Bdocs%2Fdevelop%2Funderstanding-the-javascript-api-for-office.md%5D(https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-js-docs-pr%2Fblob%2Fmain%2Fdocs%2Fdevelop%2Funderstanding-the-javascript-api-for-office.md)%0A*%20Service%3A%20**microsoft-365**%0A*%20Sub-service%3A%20**add-ins**%0A*%20GitHub%20Login%3A%20%40o365devx%0A*%20Microsoft%20Alias%3A%20**o365devx**

We will check with](https://github.com/OfficeDev/office-js-docs-pr/issues/new)

**Comment by BryanCB1** [comment]
Yes thank you

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
