### ISSUE TITLE
registerBeforeUnloadHandler is not fired when 'reload' button is clicked

### ISSUE THREAD

**Issue by ktjbrowne** [OfficeDev/microsoft-teams-library-js#2142]
Hello, 

registerBeforeUnloadHandler does fire for a change of tab or other app opened.
however, when I reload the existing tab, registerBeforeUnloadHandler does not get fired.

Would we not expect that a reload of tab should fire this?
Could we add this?

Thank you.
I'm using https://res.cdn.office.net/teams-js/2.19.0/js/MicrosoftTeams.min.js

**Comment by vikramtha** [comment]
@ktjbrowne So to better understand: When you alternate between tabs, you receive the registerBeforeUnload event. However, when you refresh the tab, you don't notice the registerBeforeUnload call.

If I am understanding this correctly, this should be the expected behavior. registerBeforeUnload only triggers when you navigate away from a tab not when you refresh the tab as you are choosing in this case to clear whatever unsaved data there was.

**Comment by ktjbrowne** [comment]
Hi Vikramtha, thanks for you response. 
To clarify fully, I am clicking the 'Reload Tab' button.

What i am trying to achieve is the ability to handle an 'end of session', this occures when we navigate away from the tab, or reload the tab.

I was hoping that registerBeforeUnloadHandler would get triggered on both cases, navigate away, or reload.

It would be great if we could somehow handle when a tab is reloaded, I would consider important in general for other solutions maybe.

Thank you.

**Comment by vikramtha** [comment]
@ktjbrowne  By design we do not want to support refresh for the handler as it is the only way for the end-user to re-initialize the app in case artifacts are not loading properly or there is some issue with the data entered. Can you go deeper into why you picture an end of session to be when the user refreshes the page? In my mind, it doesn't seem like a user would indicate end of session by refreshing.

**Comment by ktjbrowne** [comment]
Hi Vikramtha, thanks for the discussion.

In my case, I am using a Tab to display an embedded webpage.
When the user interacts with the content of the page I track the activity, when the user navigates away from the Tab I end the activity session. I was hoping that when the user Reloads the Tab to start a new interaction/session, I would also be able to handle this by listening for a Reload or Unload event.

Maybe considering your input an my proposed requirement, if we add handle a Reload event seperately then both concepts are satisfied.

Thanks you.
K.
