### ISSUE TITLE
Error loading Teams app in Microsoft365.com (errorCode: 5600, "AppID is not valid. Must be GUID format")

### ISSUE THREAD

**Issue by pablodiazgutierrez** [OfficeDev/microsoft-teams-library-js#2223]
We have 3 nearly-identical apps published on Microsoft Teams, with only different market targets. When we load them in https://microsoft365.com/, only one works, and the other two fail with a console error message stating "AppID is not valid. Must be GUID format", even though the AppID is a unique, valid GUID.

When we sideload the apps, they work fine, as confirmed by MSFT engineering staff. But once it's gone through validation and it's served through AppSource, the problems begin.

Can anyone provide any hints on what to look for?

**Comment by ChetanSharma-msft** [comment]
Hello @pablodiazgutierrez - Thanks for raising your query.
Could you please share the manifest packages so that we can test it from our end?

**Comment by pablodiazgutierrez** [comment]
> Hello @pablodiazgutierrez - Thanks for raising your query. Could you please share the manifest packages so that we can test it from our end?

Absolutely, thanks @ChetanSharma-msft, please see attached.

[pm-hipaa-1.1.27.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/14616071/pm-hipaa-1.1.27.zip)

**Comment by TrevorJoelHarris** [comment]
Hi @pablodiazgutierrez, I'm really sorry you hit this issue. I thought this was interesting and so I dug into it a little bit. I am *pretty* sure that I know what the problem is:

The app id you gave in your manifest for the app that is failing is `2b248bdc-b79d-35eb-ece8-e81c1ba9fcef`.

While that does *look* like a valid UUID it actually is not. I did some digging and found someone who actually wrote a pretty clear regex of what a valid UUID needs to be: 

`/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i` (from: https://stackoverflow.com/a/13653180)

In your case, the 17th character of any UUID has to be in the set `[89ab]`, but the 17th character of your UUID is `e`:

2b248bdc-b79d-35eb-**E**ce8-e81c1ba9fcef

Can you try uploading your app again with a valid UUID and see if that fixes the problem? Let me know!

**Comment by pablodiazgutierrez** [comment]
Thank you @TrevorJoelHarris, you're absolutely correct. There's even an open issue on the Terraform resource (random_uuid) that we invoked to create this UUID: https://github.com/hashicorp/terraform-provider-random/issues/402
So I guess the problem now is that, while Teams/Outlook and other hosts take the UUID as valid, microsoft365.com and others seem to be more strict about the UUID having to be RFC-compliant. I bet we're not the only ones running into this issue...

**Comment by TrevorJoelHarris** [comment]
> Thank you @TrevorJoelHarris, you're absolutely correct. There's even an open issue on the Terraform resource (random_uuid) that we invoked to create this UUID: [hashicorp/terraform-provider-random#402](https://github.com/hashicorp/terraform-provider-random/issues/402) So I guess the problem now is that, while Teams/Outlook and other hosts take the UUID as valid, microsoft365.com and others seem to be more strict about the UUID having to be RFC-compliant. I bet we're not the only ones running into this issue...

You're correct, I'll see about following up with some of those teams to see if we can help developers catch this earlier in the process. Thanks again for catching and reporting this!
