### ISSUE TITLE
Checking if running in Teams according to Doc does not work.

### ISSUE THREAD

**Issue by srnIxora** [OfficeDev/microsoft-teams-library-js#2229]
According to [Microsoft doc](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#teams-only-apps) this is how to check if an app is currently running in **Teams**.

But, it does not work with **Teams/V2**. Works perfectly with **Teams Classic**.

**Comment by ChetanSharma-msft** [comment]
Hello @srnIxora - Thanks for raising your query.
Could you please share the errors the you are facing?

Also, please let us know if it's not working for all New teams clients like Desktop/Web?

**Comment by srnIxora** [comment]
Hello @ChetanSharma-msft , thanks for your response. Upon further debugging I found the following:

For Teams/V2 (web):
`context.app.host.name = "TeamsModern"`

For Teams/Classic (web)"
`context.app.host.name = "Teams"`

For both cases:
`microsoftTeams.HostName.teams = "Teams"`

Most probably, that's why it was giving wrong result.

**Comment by Meghana-MSFT** [comment]
@srnIxora - As you rightly said its because context.app.host.name = "TeamsModern". It's expected for context.app.host.name to return TeamsModern in the New Teams Client (i.e. in T2.1). If app developers have taken a dependency on this name, they will need to update their logic to handle the New Teams Client correctly. We generally advise developers to be careful when using context.app.host.name in this way; if an app needs to adapt it's experience due to an unsupported API/capability, they should use the isSupported() API in that capability rather than checking the host name. You can read more about this guidance here:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#differentiate-your-app-experience
 
And microsoftTeams.HostName.teams is a constant enum value so it will always stay the same. There is an equivalent microsoftTeams.HostName.teamsModern value which will be returned in T2.1. The HostName enum and all possible values in it are documented here:
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/hostname?view=msteams-client-js-latest

**Comment by srnIxora** [comment]
@Meghana-MSFT , I understand. But is there any better way to check if an app is currently running in teams?

**Comment by AE-MS** [comment]
> @Meghana-MSFT , I understand. But is there any better way to check if an app is currently running in teams?

Hi @srnIxora! Can you tell us more about the scenario you're trying to achieve by checking if your app is currently running in Teams? We can best advise how to do that if we know more about your goals.

Thanks!

**Comment by srnIxora** [comment]
@Meghana-MSFT , nothing too fancy. Just some portion of the app will be hidden if it runs in teams.

**Comment by AE-MS** [comment]
Can you tell us more so we can ensure we have designed a good solution for you? E.g., is the portion that will be hidden because there's functionality it depends upon that's not available in Teams? Thanks!

**Comment by srnIxora** [comment]
Hi @AE-MS . Sure, here is the high level of the requirement:

- There are multiple modules. Some modules are not visible in teams. (NB: no **teams** operation)
- Call another person. Hide if not in teams.

Both can easily be handled with a simple boolean. Currently handled that with `context.name`.

Another thing, we need to send a message in teams of another person. Is there any process that can be achieved in both cases (in teams and not in teams)?

Currently, handle with this `MSTeams:/l/chat/0/0?users`. There is a beta api in sdk for teams environment. As it is not stable we did not use it.

Thanks.

**Comment by alexnault** [comment]
@srnIxora We have used this snippet for the past 2 years to determine if we are running in a MS Teams window:

```js
function checkInTeams() {
  return (
    (window.parent === window.self && (window as any).nativeInterface) ||
    window.navigator.userAgent.includes('Teams/') ||
    window.name === 'embedded-page-container' ||
    window.name === 'extension-tab-frame'
  );
};
```

 It works in both Teams Classic and the new Teams.

Cheers!

**Comment by jekloudaMSFT** [comment]
Hi @srnIxora, I think the best way to handle this scenario would be using the [`isSupported`](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/chat?view=msteams-client-js-latest#@microsoft-teams-js-chat-issupported) method on the appropriate capabilities (`call`, `chat`, etc.) to determine what functionality is available in the host and use that logic to display the appropriate modules. The `chat` capability was just released out of beta, so you can safely call that capability using the beta API in your current teams-js version or wait to pick up the release version of `chat` in the next monthly teams-js release. Would this fully cover your use case?

**Comment by srnIxora** [comment]
@alexnault , @jekloudaMSFT  thanks.
