### ISSUE TITLE
Throws `TransientError` when calling `authentication.getAuthToken`

### ISSUE THREAD

**Issue by rickygao** [OfficeDev/microsoft-teams-library-js#2317]
Hi team, we are sometimes getting `TransientError` when calling `authentication.getAuthToken`. Do you know what this means? How can user recover from this?

```
{
  "Description": "(pii)",
  "Domain": "com.microsoft.oneauth",
  "ErrorCode": "3205",
  "Message": "Transient system error.",
  "SystemErrorCode": "2148008704",
  "Tag": "657rw",
  "Type": "OneAuth",
  "additional_query_parameters_count": "1",
  "all_error_tags": "657rw|657rw",
  "api_error_code": "2148008704",
  "api_error_context": "(pii)",
  "api_error_tag": "657rw",
  "api_name": "AcquireTokenSilently",
  "api_status_code": "StatusInternal::TransientError",
  "auth_flow": "Broker|Broker|Broker|Broker|Broker|Broker|Broker",
  "authority_type": "AAD",
  "authorization_type": "WindowsIntegratedAuth",
  "broker_app_used": "true",
  "broker_error_location": "657rw",
  "client_id": "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
  "correlation_id": "5bc314f8-9e32-4016-b547-35d47f604bc1",
  "delete_token": "AT",
  "is_successful": "false",
  "msal_version": "1.1.0+00747db6",
  "original_authority": "https://login.microsoftonline.com/4918c2bf-3073-4bc3-a44f-e06b4219b7c4",
  "read_token": "ID|EAT|ID|ID|ID|ID|ID|ID",
  "request_duration": "63287",
  "request_eligible_for_broker": "true",
  "start_time": "2024-05-06T13:54:18.000Z",
  "stop_time": "2024-05-06T13:55:21.000Z",
  "was_request_throttled": "false"
}
```

**Comment by Prasad-MSFT** [comment]
@rickygao - The `TransientError` you're encountering when calling `authentication.getAuthToken` indicates a temporary issue with the authentication service. This could be due to network instability, service outages, or other transient conditions that prevent the authentication token from being obtained successfully.

Since the error is transient, you may attempt to request the token again after a short delay and verify if there are any known issues with the Microsoft authentication service that could be causing this error. Also, ensure that your app's authentication settings are correctly configured and that it has the necessary permissions.

**Comment by rickygao** [comment]
@Prasad-MSFT Thanks for your answer.
