### ISSUE TITLE
OneDrive file picker SKD

### ISSUE THREAD

**Issue by LeoM93** [OfficeDev/microsoft-teams-library-js#2356]
I have the following Issue: I'm trying to open the oneDrive file picker (https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online) but when I try to authenticate, I receive the following error and the pop up login window is white:

`Error: SDK initialization timed out.
    at gt (app.ts:55:7)
    at e.initialize (app.ts:767:12)
    at auth-end.html:25:26`

In more details, I used Teams toolkit to create an Teams tab app. when provisioning, it automatically create an Azure Active Directory registering the app, generating a new client secret and adding a new web platform with an redirect url: https://nice-wave-0a8f4d710.5.azurestaticapps.net/auth-end.html

This is the code in the auth-end.html:
<img width="581" alt="Screenshot 2024-06-12 at 15 19 45" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/22978241/3108e069-b072-4275-a1af-2382b4f0aaae">
Can you help me debugging the problem?

Thank you in advance for the help

**Comment by KangxuanYe** [comment]
Hello @LeoM93, thanks for reporting the issue. To better assist you, I would like to double confirm some of basic info with you first. Please feel correct me for points I listed below

Based on your description and screenshot provided,

- This initialization timeout issue happens when the app is working on authentication
- You are using Teams-JS library V2.22.0
- You are running this Teams Tab App on Teams (web)

And then I have following questions:

- Which Teams version you are running on? Is it old Teams or new Teams? (I am assuming you are running on Teams Web)
- Where did you observe this initialization timeout issue? Usually there will be a dialog or another web page for authentication. If you can observe it, could you please try to follow this [instruction](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#enabling-logging) to enable client logging and send as much logs as possible to us?
- Are you able to reproduce this initialization timeout issue on your side?

Meanwhile, I will try to follow your steps to write a sample app to see if I can reproduce this.

**Comment by KangxuanYe** [comment]
Hi @LeoM93, I also followed your instruction and constructed a demo app on cloud by using Teams Toolkit. I clicked the `provision` under Lifecycle and then deployed the app. I could see my app is registered in AAD but I didn't get a new client secret and redirect url as you did. Could you please share more information to me in case I miss something? Also we would appreciate if you can let us know more detail about what to do to add an authentication for the app. Thank you so much.

**Comment by KangxuanYe** [comment]
Reopen this issue for waiting response from author to answer in another week. This will be closed if nothing is heard at the end of next Monday, July 1st, 2024.
