### ISSUE TITLE
Add `allow-top-navigation` to result iframe 

### ISSUE THREAD

**Issue by MicroAsif** [OfficeDev/microsoft-teams-library-js#246]
I'm using stripe new version of  payment api which requires allow top navigation. 
here is the issue that i l'm facing while using app under ms teams.  
https://github.com/jsfiddle/jsfiddle-issues/issues/1445

**Comment by ydogandjiev** [comment]
Hi @MicroAsif, thank you for raising this issue. Unfortunately, we cannot set the `allow-top-navigation` permission on our iframes because that would allow any of our hosted apps to redirect the Teams top-level window to a different site thus degrading the user experience and potentially posing a security risk (e.g. via redirect to a site that spoofs Teams and attempts to swipe the user's credentials).

I would recommend reaching out to the owners of the API you're using and asking them to provide a version that does not attempt to re-navigate the top-level window (e.g. by specifying `target="_blank"` instead of `target="_top"` on anchor tags and/or calling `window.open(<url>, "_blank")` instead of `window.open(<url>, "_top")`.
