### ISSUE TITLE
Silent Azure AD authentication is broken

### ISSUE THREAD

**Issue by Titaye** [OfficeDev/microsoft-teams-library-js#282]
Silent authentication is broken due to this issue : https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/773

Is there a workaround to apply with the sdk to make it working ?

Thanks !

**Comment by ydogandjiev** [comment]
Hi @Titaye, silent authentication in Teams will only work if:
1. Your app requires no additional user consent (i.e. you have tenant admin consent or the user has already consented in the past)
2. Your app has no additional Conditional Access policies beyond those set on Teams (this is controlled by the tenant admin and might vary from one organization to the next)
3. An active AAD session has already been established within the current context (i.e. in the Teams Desktop Client or the browser). In the browser the session will always be there because the user must have established it when logging into Teams; however, our Desktop Client uses native ADAL which means that just because the user is signed into Teams doesn't mean that there is an established AAD session.

If the `authContext._renewIdToken` call fails which it will if one of the conditions above isn't met then you are supposed to fall back to a popup auth flow as described here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad

**Comment by Titaye** [comment]
Hi @ydogandjiev 

Thanks for answering. I perfectly understand that in some case the silent auth is not possible. But when it should work I get a javascript error telling the hidden auth iframe cannot finish the last redirect and so shows the login button. It's not a case when it should appear.

`The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.`

As I tried to explain in the issue https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/773#issuecomment-521163058 , I think the adal lib is trying to manipulate the wrong window. So I don't know if it's something you have to enable from MSTeams side, but at the end, I can't make your silent auth working

**Comment by adamcherry** [comment]
@Titaye I'm having the exact same issue, and it started happening only recently...

**Comment by Titaye** [comment]
> @Titaye I'm having the exact same issue, and it started happening only recently...

Thanks for reporting it. At least I'm not alone :). Things are not as straight forward as it should.

**Comment by DarylThayil** [comment]
So I could be wrong, but I don't think adal has had the changes that would cause errors like this to start appearing.

My hunch is that iframes that were not sandboxed are potentially being sandboxed now.
Adal did have some issues that are fixed in MSAL (which if you are able to I highly recommend moving to) where it would impolitely try and redirect the top frame. 


Can anyone comment on if any other variables have changed in the set up

**Comment by ydogandjiev** [comment]
Hey @DarylThayil, thank you for looking into this issue! The iframe we use to host tabs in Teams has been sandboxed from the very beginning (3+ years now) and we haven't made any changes to it for some time now. Do you have any idea what logic in ADAL.js attempts to trigger the top frame redirection on silent token refresh? Is there a way to suppress it via configuration options?

**Comment by rwormsbecher** [comment]
@Titaye , @ydogandjiev  I had this issue as well, it turned out to be an issue with the redirect url within Azure. Once I fixed that it worked. I have a repo online which you could try to make it work: https://github.com/rwormsbecher/Microsoft-teams-tab-authenticaion-with-adal
