### ISSUE TITLE
getSettings() does not ever fire the callback method

### ISSUE THREAD

**Issue by wictorwilen** [OfficeDev/microsoft-teams-library-js#32]
I can't get the `getSettings()` to ever call back my callback, in version 0.4.
Known issue?

I use the the following code

> microsoftTeams.settings.getSettings( (settings:any) => {
>     console.log('you will never see me');
> )}:

**Comment by dfederm** [comment]
Can you confirm that you are calling this on the settings frame? microsoftTeams.settings.getSettings is only available to the settings frame and not the tab content frame.

If you are calling it from an unsupported context, you should see your call throwing an error as well along the lines of "This call is not allowed in the 'content' context"

**Comment by wictorwilen** [comment]
Ah. It's on the content tab, however I don't see the exception you mention.
How do I access settings in the content tab?

**Comment by dfederm** [comment]
Oh, interesting, I'll have to look into it further but I believe that if you call any function that's not available in that context but initialization hasn't finished yet (it's async but we queue up the subsequent calls for you as needed), we don't throw the exception.

Today there is no way to get the settings from the content tab, however the `microsoftTeams.getContext` call should have most of what you need. What specifically is on the settings which you need in the content frame?

**Comment by wictorwilen** [comment]
Thanks, get `getContext()` does not give me the custom properties I store in the configuration tab. Isn't the configuration tab supposed to be used for configuring, or is the only way to pass configuration properties via the query string in the content url?

**Comment by dfederm** [comment]
The customSettings field was deprecated in v0.4 and was actually only provided to help restore the settings page when updating (as opposed to potentially having to parse your url to reverse-engineer whatever settings the user chose on your settings page. It wasn't intended to store data for the content frame. You can do that by either encoding the data in the content URL itself (query params for example as you mention) or store a blob server side keyed on the entityId you provide and/or other fields on the context depending on the scope you need the setting to be keyed off of.

**Comment by Damovisa** [comment]
@dfederm I'm aware this was closed, but having to store settings data on our server, or even receive requests with credentials in the URL is problematic for us.

Our application is self-hosted by the customer, so we never know their credentials (nor do we want to). The intention was to let the user save credentials as `customSettings` on the config page, then serve a "shell" content page in the iFrame containing javascript which would:

- Load `customSettings` from Teams
- Use those `customSettings` to make API calls against their own self-hosted installation
- Render a nice UI

After the initial html/js page is loaded in the iFrame, all of the communication would therefore between the browser and Teams, or the browser and their local application. The server hosting the "shell" page wouldn't ever receive sensitive details.

We don't provided a hosted offering of our product, but it looks like we'd currently have to collect credentials on the server anyway - even if it's just through query strings in the URL.

Is there likely to be a way around this?

**Comment by dfederm** [comment]
@Damovisa Who's credentials would you be saving in this case? `customSettings` was per tab, not per-user per-tab, so what you described is for the user who configures the tab to authenticate, stash the token in a place where anyone in the Team can get it, and for any other user to reuse that same token forever. Also, how would token-refresh work?

I'm not sure what you mean by your application never knowing their credentials. A typical auth flow will popup the auth provider (like AAD) which will end up providing you with a token (not raw credentials). Your application would "know" the same amount of information as you described in this case, and the token would be only stored in the user's cookie jar (typically).

**Comment by Damovisa** [comment]
@dfederm Thanks for the reply. The credentials would normally be for a service account. The tab would simply show information, but if they wanted to perform tasks, the user could be redirected to the application itself to log in. So a shared service account is fine.

I'll take a step back to try to explain the architecture.

The application with the data we want to show is our product, but *it's installed and hosted by the user on their own infrastructure*. It exposes an API that can be accessed via a REST endpoint, passing in a PAT-style API key. There's no real "flow" here. Just an auth token that can be revoked if the need arises. _As a company_, we're not involved here - auth all happens inside their infrastructure and we don't control it. We don't want to see those details - which is what happens if the custom settings (the URL and API key) are sent with the request for the iFrame contents.

Typically, integration from a third party application occurs via the REST API. The user provides a URL for their instance (e.g. https://myappserver) and an API key, and the application or extension calls the API at that endpoint using the API key.

We were hoping that in Teams, the user who set up the tab would be able to provide these pieces of information, then the content could be retrieved directly from the browser.

The sensitive information would therefore be stored by Microsoft Teams, and would only be used from the browser to call into their own infrastructure.

Here's a quick and dirty picture of the flow we were hoping for.

![image](https://cloud.githubusercontent.com/assets/1887732/25156488/e4d3c1ba-2468-11e7-9099-d46af8a74bfb.png)

**Comment by dfederm** [comment]
@Damovisa One thing you can try, and one of the other reasons we decided to deprecate customSettings instead of start exposing it to the content frame, is to use the entityId.

The entityId is intended to be the unique developer-defined id for the content. As an example for a planner tab, the plan id would be this entity id. Our thought is that tabs which had "lots" of tab instance data would use this id as a key to their data storages. However, there's nothing stopping you from using it in other ways too, for example, the api key in your scenario, so long as it is also unique to that content.

By unique here I mean that if the same tab was added to two different channels, they should have the same entity id. If this isn't unique, ie the same content can be viewed with multiple API Keys (and thus different entity ids) then this isn't really recommended and instead we recommend passing it in the url as you mentioned. Using the same example above, the entityId would be the plan id, but something like a "sort by date" field should be in the url. I do understand the aversion from storing in the url however.

Let me know if the entityId actually does work for you or if storing the key in the url works.

**Comment by Damovisa** [comment]
@dfederm 
I successfully got it to work by storing the API key in the URL, but of course that means we learn the user's credentials, which we don't want.

If we used the entity id, is there are restriction on the size and shape of that ID string? For example, could we encode the two bits of data we need - application URL and API Key - in that field, then decode on the client side? If so, that'd solve the problem for us.
