### ISSUE TITLE
[Question] access to User Presence 

### ISSUE THREAD

**Issue by nullptr023** [OfficeDev/microsoft-teams-library-js#343]
Hi Microsoft Teams,

Is it possible to have access to the user presence information of current user? If it is, is there a way to register a callback function when the user presence changed. For instance, when the user changed the status to available to busy, do not disturb, be right back or appear away, the callback function will be called each time it is changed. 

Thank you.

**Comment by ydogandjiev** [comment]
No, the Client SDK doesn't provide access to data available in the Graph since:
a) The Teams or other Office Client hosting your app isn't guaranteed to have the information.
b) We don't have a good way of enforcing the same rich permissions model that the Graph provides via its scopes.

To get the user presence, please use the following Graph API:
https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http
