### ISSUE TITLE
How to getChatMembers from Task module ?

### ISSUE THREAD

**Issue by unckleg** [OfficeDev/microsoft-teams-library-js#385]
- How to getChatMembers from Task module ?

**Comment by ydogandjiev** [comment]
To get the roster of a group chat please use our Graph APIs:
https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http

The `getChatMembers` SDK API is not publicly documented and not currently exposed to any of our apps. We do not have any plans to change that currently since our platform lacks the rich client-side permissions model in place necessary to keep these kinds of data flows secure and compliant.

**Comment by unckleg** [comment]
So if I go with using the Graph API that you are referring to, even if that's a BETA API and will not work on production apps but nevermind. 

Let's reopen this since I'm not able to get nor meetingId nor chatId, without that I'm unable to use referred BETA API.

Here is the ref to those: #386 #384.

Thanks!
