### ISSUE TITLE
[Question] How to run e2e tests on a custom tab in teams?

### ISSUE THREAD

**Issue by RobPethick** [OfficeDev/microsoft-teams-library-js#397]
I'd like to write some end to end tests on my app which exists as a custom tab within teams. I'm a bit daunted about how to start, will it be possible to get Selenium, Cypress or similar to log in with some microsoft credentials I set up? 

Or will I have to fake the teams frame? If so is there any instructions on how to mock some of the teams SDK particularly the getContext call?

**Comment by Gousia-MSFT** [comment]
@RobPethick For getContext in particular, we would recommend  passing the data through URL placeholders. This makes it easier to test the tab in isolation, and it's also faster as you can avoid waiting for both initialize() and getContext().
 
For a true end-to-end test, you could try using Selenium .

**Comment by RobPethick** [comment]
@Gousia-MSFT - thanks for the answer - could you expand a bit more on what you mean by URL placeholders?
Do you mean pass a dummy context as query params and read it from there rather than calling getContext in my method

**Comment by Gousia-MSFT** [comment]
@RobPethick  You could get the Tab context by passing the URL placeholder from the manifest file instead of calling getContext. Please take a look at [Getting context using URL placeholders](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#getting-context-by-inserting-url-placeholder-values).
