### ISSUE TITLE
microsoftTeams.authentication.authenticate() call on Teams desktop client open a browser window instead of desktop client popup and break the authentication flow

### ISSUE THREAD

**Issue by idevrnd** [OfficeDev/microsoft-teams-library-js#458]
SKD version: 1.8.0
Angular 8

microsoftTeams.authentication.authenticate()  authentication call on the Teams desktop client open an external browser window instead of a desktop client popup and break the authentication flow.  No way to notify  the desktop client from the browser tab using microsoftTeams.authentication.notifySuccess() since the auth flow is already broken

**Comment by Nikitha-MSFT** [comment]
We are looking into the issue we will get back

**Comment by Nikitha-MSFT** [comment]
we are not able to repro the issue at our end. Could you please check this [example](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/tree/master/src/views/tab/sso)?

**Comment by cas--** [comment]
I have been facing seemingly the same issue with an AngularJS application. The issue arises when attempting to authenticate via a Tab in the MS Teams Desktop app and it opens in a browser tab instead of a popup as normally happens at teams.microsoft.com. 

Our setup has a controller with an `authenticate` method that is called by a button `ng-click` directive. 

```javascript
function MicrosoftTeamsAuthenticationController(...) {
  const ctrl = this;
  ctrl.authenticate = function () {
    $window.microsoftTeams.initialize();
    $window.microsoftTeams.authentication.authenticate({
      url: config.BASE_URL + '/app/microsoft-teams/tabs/auth',
      width: 600,
      height: 535,
      successCallback: onAuthSuccess,
      failureCallback: onAuthFailure,
    });
  };
  ...
}
```

I have seen this issue discussed on [techcommunity](https://techcommunity.microsoft.com/t5/microsoft-teams/authentication-authenticate-opens-in-external-browser-tab/m-p/1410311) which mentions that the call to `microsoftTeams.initialize` seems to be the culprit. So I tried a workaround where the call `microsoftTeams.initialize` is performed while setting up the controller instead of in the authenticate method:

```diff
function MicrosoftTeamsAuthenticationController(...,  angularLoad) {
  const ctrl = this;
+  angularLoad.loadScript('https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js').then(() => {
+    $window.microsoftTeams.initialize();
+  });

  ctrl.authenticate = function () {
-    $window.microsoftTeams.initialize();
    $window.microsoftTeams.authentication.authenticate({
      url: config.BASE_URL + '/app/microsoft-teams/tabs/auth',
      width: 600,
      height: 535,
      successCallback: onAuthSuccess,
      failureCallback: onAuthFailure,
    });
  };
  ...
}
```

This does work but I feel that this is still a bug that should be fixed since this works fine in browser but is broken in the Desktop app...

**Comment by ydogandjiev** [comment]
There is a more full proof way to fix this. All you need to do is wait for the initialization to compete before calling the authenticate API:
```
microsoftTeams.initialize(() => {
  microsoftTeams.authentication.authenticate({
    ...
  });
});
```

**Comment by cas--** [comment]
@ydogandjiev Yes I am aware that was a possibility because `initialize` is an async function however this is a button click and so the indirect call to `authenticate` will cause the browser to block the popup and Microsoft Internal testing will fail the product validation over this!

**Comment by ydogandjiev** [comment]
> @ydogandjiev Yes I am aware that was a possibility because `initialize` is an async function however this is a button click and so the indirect call to `authenticate` will cause the browser to block the popup and Microsoft Internal testing will fail the product validation over this!

That's a good point; I guess in that case your only option is to make the `microsoftTeams.initialize()` call as soon as your page loads (which is generally the recommended option anyway) and show a spinner or some kind of progressive load UX until the initialization completes before showing the "Login" button. The SDK needs to know if your app is being hosted in our of our native clients vs the browser so it can adjust the behavior of the `authenticate` API; the only sure way to know that today is by waiting for the initialization response that the Teams Client sends back with the necessary information.
