### ISSUE TITLE
Field `TabInstance.lastViewUnixEpochTime` is never populated

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#466]
1. Call `getTabInstances(callback)`.
2. Examine the results passed to the callback.
3. Observe that documented field `lastViewUnixEpochTime` is always missing from every tab (even tabs that I visited moments ago and even tabs that I'm currently visiting), and is never `null` as it is documented to be when the value is unknown.

See incorrect documentation at https://github.com/OfficeDev/microsoft-teams-library-js/blob/f2b33e1498d127440c44c4d8d5bdf456a20d93b9/src/public/interfaces.ts#L26-L29

**Comment by ydogandjiev** [comment]
Hey @ascott18, the `lastViewUnixEpochTime` property is only set for tab instances retrieved via the [getMruTabInstances](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#getMruTabInstances__tabInfo__TabInformation_____void__TabInstanceParameters_) API.

**Comment by ascott18** [comment]
@ydogandjiev Is there a specific reason for this limitation? I don't want to fetch only what the Teams algorithm determines to be the MRU tabs. I want to have an API that is guaranteed to always fetch all the tabs and from there I will take care of sorting myself, but I can't do the sorting according to my application's needs if the non-MRU version of this function arbitrarily omits the timestamps.

**Comment by ydogandjiev** [comment]
The two APIs are fetching data from completely different sources:
- The `getTabInstances` API finds all instances of your tab that are pinned across all of the user's teams & channels (though it's limited by what the client has cached locally). The tab instances returned by this API are the same for every user who is also a member of those teams/channels. It's possible that the current user has never have visited any of these tabs so a last viewed time might not even be available. Even if they have visited these tabs, the time stamp of such a visit is not stored on the tab instances themselves because it's different for every user.
- The `getMRUTabInstances` API makes a network call to first fetches a list of recently visited tab instances. This list is maintained in a completely different data store and indexed by the user's ID. This list would be different for each user and could be empty if they've never visited one of your channel tabs.

If you want to display a list of all your app's tabs across the user's teams with the MRU ones on top then your best option is to call both APIs in parallel and then merge their responses. Did you give this a shot?

**Comment by ascott18** [comment]
Thank you, that makes sense. Calling both and merging will work.

It may be worth adding a note to the Typescript doc comment that the field is only populated with `getMruTabInstances`. Or to the doc for `getTabInstances` to note that it won't populate `lastViewUnixEpochTime`.

Thanks again for your help!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
