### ISSUE TITLE
`getTabInstances` always returns empty list when called from a static tab

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#467]
1. Open one of your app's static tabs
1. Call `getTabInstances(callback)` from code running within that static tab
1. Observe that the result set returned to the callback is always an empty array.
1. Do the same operation from a team tab - observe that the array is correctly populated.

**Comment by ydogandjiev** [comment]
@ascott18, you're probably hitting this issue because of sideloading. Each time you upload a custom app in a team or personally you are creating a new app instance with a unique ID. Therefore, your personal app is actually different from your team app which is why the `getTabInstances` API returns no tabs in the personal scope.

To ensure that your personal and team app are one and the same you can either:
1. Upload the app only into one of your teams and then search for it via the power bar and install it personally via the banner:
![image](https://user-images.githubusercontent.com/3357245/101578154-9ef61a00-398e-11eb-9745-4266179b1d09.png)

2. Upload the app to the tenant catalog and install it from the Apps Store (for this you need an a tenant admin account):
![image](https://user-images.githubusercontent.com/3357245/101578273-a61d2800-398e-11eb-9bf5-d2a9e35421b2.png)

**Comment by ascott18** [comment]
You're absolutely right, my apologies. In this case it was not due to sideloading, but rather due to the fact that the app review team kept bricking our marketplace offering and they couldn't figure out how to un-break it, forcing us to just keep creating new ones until they could get it right. My static tab ended up with a different ID than all the actual teams tabs (there are 13 teams tabs spread over 3 different AppIds).
