### ISSUE TITLE
microsoftTeams.shareDeepLink does not work as expected

### ISSUE THREAD

**Issue by sr258** [OfficeDev/microsoft-teams-library-js#498]
I try to generate a deep link to a subEntityId in a Microsoft Teams group tab. When I call

```
microsoftTeams.shareDeepLink({
  subEntityId: "myid",
  subEntityLabel: "123"
}
);
```

I get this dialog (my tab is called 'Interactive'):
![image](https://user-images.githubusercontent.com/15268740/106422083-38f1b480-645e-11eb-9d76-5234ee6aec5b.png)

As you can see, there is no URL in the text field but the label, which was suffixed with the tab's name. If I press Ctrl + C I get this - not very useful - text string in the clipboard, not a URL. I'm aware of the documentation at https://docs.microsoft.com/de-de/microsoftteams/platform/concepts/build-and-test/deep-links but this more looks like a bug in microsoftTeams.shareDeepLink. (Sidenote: Generating the deep link as described in the docs also doesn't work).

I use the npm package @microsoft/teams-js with version 1.8.0 and the manifest version of my teams app is 1.8.

**Comment by ydogandjiev** [comment]
@sr258, this functionality is currently by design. The copied link is in rich text format and can only be pasted in an editor that supports rich text (e.g. Outlook, Word, Teams itself, etc.):
![image](https://user-images.githubusercontent.com/3357245/106547885-e4cceb80-64c2-11eb-8fd0-db7c572f955d.png)

The URL is too long and ugly to copy as plain text and we expect that most users will send these link via e-mail or paste them in Teams chats where they work without issue.
