### ISSUE TITLE
How is a failure on ' getAuthToken()' to handle and how can one reproduce the behaviour without another tenant.

### ISSUE THREAD

**Issue by marwalsch** [OfficeDev/microsoft-teams-library-js#540]
Using the `getAuthToken()` API works for members within the own tenant as the required Graph scopes are permitted by default. However, before deploying the app to another tenant I obviously want to test the behaviour on initial failure which is expected to occur on the first time the app is used by another organisation's member. I am aware that in a production scenario an MPN registration is required. 
As far as I am aware, the failure occurs when the Graph scopes required to get an access token have not yet been granted (such as User.Read, email, etc.). In that case, the failure callback is initiated and the token won't be acquired. What now? Observing a production app using SSO (Polly to be more specific) the notorious "[Almost there!](https://docs.microsoft.com/de-de/microsoftteams/platform/assets/images/tabs/tabs-sso-prompt.png)" dialogue opens up as expected. Up to this point the flow can be reproduced inside the own tenant by omitting the pre-consent for the Teams clients, while upon consenting an AAD error occurs (this could've been expected also, I was just experimenting). Forcing the dialogue to show up by revoking the permissions as suggested [here ](https://github.com/MicrosoftDocs/msteams-docs/issues/1898)does not work; my app doesn't appear here since `getAuthToken()` worked right away for me without ever consenting (while other apps registered by me show up for some reason) This raises a number of questions:

_How can I force the consent pop-up to show up for my own tenant, or at least myself?_

_How does granting consent actually work?_ Is this entirely handled by teams or do you have to redirect to the log-in screen for Graph as a few samples suggest. If so, why do all these [samples ](https://github.com/MicrosoftDocs/msteams-docs/issues/1898) receive and use tokens from Graph's authN endpoint while the apparent purpose is to merely tell Graph that it's fine for the app to retrieve the required permissions for log-in purposes. 

_Can you completely avoid handling consent and the MDN registration by requiring other tenants to use the pre-consent url?_ (`https://login.microsoftonline.com/common/adminconsent?client_id=<AAD_App_ID>`).

**Comment by Sridevi-MSFT** [comment]
@marwalsch, Taking this for internal discussion with team and will update you.

**Comment by Sridevi-MSFT** [comment]
@marwalsch- To get the correct token for Microsoft Teams Free and guest users, it is important that the apps use tenant specific endpoint https://login.microsoftonline.com/**{tenantId}**. You can get tenantId from the bot message or tab context. If the apps use https://login.microsoftonline.com/common, the users will get incorrect tokens and will log on to the "home" tenant instead of the tenant that they are currently signed into. Please check this [sample](https://github.com/ydogandjiev/taskmeow).

**Comment by marwalsch** [comment]
@Sridevi-MSFT Isn't the `getAuthToken()`-API defaulting to the correct (current) tenant? It works as stated but I am still wondering how one can consistently reproduce the Pop-out appearing without having to wait hours each time after the rights have been revoked. Or even better, get the Pop-up to appear for registrations within the on tenant. Might the admin be abe to revoke default Graph permissions to an extend that this will work. 
I am also still curious about the apparent missing necessity of the MDN registrations within the same domain space.

**Comment by marwalsch** [comment]
@Sridevi-MSFT Perosnal, free or guest user accounts are of no concern, as only native business accounts are among the users. The personal account was just used to have a 2nd tenant.

**Comment by Sridevi-MSFT** [comment]
@marwalsch - If an app has tenant admin consent then that needs to be revoked first in order for the prompt to show up. Otherwise, if the user has personally consented to an app they can revoke their own consent from https://myapplications.microsoft.com.


![SS002](https://user-images.githubusercontent.com/80752198/117981081-40c0cf00-b352-11eb-8d40-cfa91772cc0d.png)
![SS001](https://user-images.githubusercontent.com/80752198/117981106-48807380-b352-11eb-8893-f5aecce3461d.png)
