### ISSUE TITLE
getAuthToken returns resourceRequiresConsent on some tenants

### ISSUE THREAD

**Issue by el** [OfficeDev/microsoft-teams-library-js#691]
Hi, we implemented SSO for teams using the guide here:

https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso

On some tenants (specifically the demo tenant used by the store team) `authentication.getAuthToken` returns the error message `resourceRequiresConsent`

Keep in mind that the app works as expected (returns an authToken) for the other tenants.

I couldn't find anything to help me with this.

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. We will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Any console error you are getting? We tried to repro, but it worked fine for us.

Thanks

**Comment by el** [comment]
Heyy. Please send me an email at eliz[at]unscrambl.com so I can share the steps to reproduce.

**Comment by ydogandjiev** [comment]
This is expected because each tenant can independently configure the CA policies for yours and any other AAD apps in the organization. If you get a resourceRequiresConsent error then you need to call getAuthToken again and not specify the silent parameter or set it to false. This will trigger the necessary interactive flow for the customer to provide consent.
