### ISSUE TITLE
Question about the getUserJoinedTeams method and a possible feature request for getTabInstances.

### ISSUE THREAD

**Issue by olafur164** [OfficeDev/microsoft-teams-library-js#776]
Hello, we've been getting joinedTeams related data for a user from the Graph API so far but all the teams related graph endpoints have a lot of throttling limitations so we've been looking into how we can improve the performance of our app but utilizing the teams SDK, and I came across the getUserJoinedTeams method in the source code of the SDK but it seems that the Promise never resolves. Is the getUserJoinedTeams method only for use for first party apps or is it possible that third party apps could use it? If not I'm wondering if the return from getTabInstances could include the isTeamArchived and teamType property?

also regarding the getTabInstances, what is the status of https://github.com/OfficeDev/microsoft-teams-library-js/issues/544

**Comment by Nivedipa-MSFT** [comment]
@olafur164 - We are looking into this issue. We will get back to you.

**Comment by Nivedipa-MSFT** [comment]
@olafur164  
1. getUserJoinedTeams method only for use for first party apps.
2. getTabInstances returns TabInformation which is not include isTeamArchived and teamType property. This is by design. The TeamInformation interface contains isTeamArchived and teamType property.
[TeamInformation](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.teaminformation?view=msteams-client-js-latest)

**Comment by v-chetsh** [comment]
@olafur164 - Please let us know if you need any further help here?
