### ISSUE TITLE
[Enhancement] Allow to securely sign out, including clearing cookies inside Electron app

### ISSUE THREAD

**Issue by Ky7m** [OfficeDev/microsoft-teams-library-js#86]
Would be great to have an additional method that allows to make a sign-out call from 3rd party service and clear all session/cookies for this specific domain to avoid "auto-login" with the previous session (something similar to microsoftTeams.authentication.authenticate method but it also clear auth cache for the specific domain inside Electron app).

**Comment by billbliss** [comment]
To be accepted in the store, we actually require a "Sign Out" link but that's something initiated by a user. 

It's not possible for Teams to clear the cookies for another domain...or rather, since we are effectively the browser in that case, it's technically possible but doesn't seem advisable. 

Can you elaborate a bit more on the use case you envision, and why a user-initiated sign-out isn't adequate?

**Comment by Ky7m** [comment]
I am so sorry for the very late response. The issue was resolved on our end.
